using System.Diagnostics;

namespace LibSolowej.Operator
{
    /// <summary>
    /// Provides a noise module that caches the last output value generated by a source
    /// module. [OPERATOR]
    /// </summary>
	[ModuleMapping(ModuleTypes.Modifier, "buffer")]
    public class Cache : ModuleBase
    {
        #region Fields

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of Cache.
        /// </summary>
        public Cache()
            : base(1)
        {
        }

        /// <summary>
        /// Initializes a new instance of Cache.
        /// </summary>
        /// <param name="input">The input module.</param>
        public Cache(ModuleBase input)
            : base(1)
        {
            Modules[0] = input;
        }

        #endregion

    }
}